<?php
$this->layout('../layouts/layout',
[
    'titles'=> 'FBMinimarket | Productos'
]);
?>
<?php $this->push('styles');?>
<!-- //link de css  -->
<?php $this->end(); ?>

<?php $this->start('contents');?>

<div class="container">
    <h1>Producto</h1>
    <div class="row">
        <div class="col-sm-4 form-group">
            <a is-modal="true" href=" <?=URL . 'producto/detail'?>" class="btn btn-primary btn-block">Nuevo</a>
        </div>
        <div class="col-sm-5 form-group">
        </div>
        <div class="col-sm-3 form-group">
            <div class="btn-group dropright">
            <button type="button" class="btn btn-secondary">
                Estado
            </button>
            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu">
                <a href="<?=URL. "producto" ?>"class="btn  text-primary"> Activos</a>
                <a href="<?=URL. "producto/index/0" ?>"class="btn text-info"> Inactivos</a>
            </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover">
                <thead  class="thead-light">
                    <tr>
                        <th style="width:5%;">ID</th>
                        <th style="width:5%;">Marca</th>
                        <th style="width:5%;">Categoria</th>
                        <th style="width:5%;">Unidad</th>
                        <th style="width:20%;">Nombre</th>
                        <th style="width:30%;">Descripcion</th>
                        <th style="width:10%;">Precio costo</th>
                        <th style="width:10%;"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php  foreach($data as $row):  ?>
                    <tr>
                        <td> <?=$row->Id ?></td>
                        <td> <?=$row->IdMarca ?></td>
                        <td> <?=$row->IdCategoria ?></td>
                        <td> <?=$row->IdUnidad ?></td>
                        <td> <?=$row->Nombre ?></td>
                        <td> <?=$row->Descripcion ?></td>
                        <td> <?=$row->PrecioCosto ?></td>
                        <td>
                        <a is-modal="true" href="<?=URL. "producto/detail/{$row->Id}" ?>" class="btntb btn-success btn-sm"> <i class="fa fa-pencil"></i></a>
                        <a href="<?=URL. "producto/delete/{$row->Id}" ?>" class="btntb btn-danger btn-sm"> <i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <?php  endforeach;  ?>
                </tbody>
            </table>
        </div>
        <br>
    </div>
</div>
<?php $this->end(); ?>

<?php $this->start('myModal') ?>
<?php
$title = 'Producto Detalle - Insertar';
$size = MUYGRANDE;
include MAINPATH . 'app/views/layouts/partials/_areaModalCrud.phtml';
?>
<?php $this->stop() ?>


<?php $this->push('scripts');?>
  <script src="<?=URL.'js/scripts/modal_crud.js'?>"></script>
<?php $this->end(); ?>