<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form id="myForm" action="<?=URL .'marca/save'?>" method="post">
                <input type="hidden" name="Id_marca" value="<?=$data->Id?>">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="nombre">Nombre</label>
                            <input type="text" name="nombre" id="id_nombre" class="form-control" required
                               maxlength="14" value="<?=$data->Nombre?>">
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="nombre">descripción</label>
                            <input type="text" name="descripcion" id="id_descripcion" class="form-control"
                                value="<?=$data->Descripcion?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group form-check">
                            <input type="checkbox" name="estado" id="id_estado" class="form-check-input"
                                <?= ($data->Estado == 1) ? 'checked' : '' ?>>
                            <label class="form-check-label" for="exampleCheck1">Estado</label>
                        </div>
                    </div>
                    <div class="form-group col-sm-8 ">
                        <div class="" id="mis_errores">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Guardar </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
