
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="<?=URL .'usuario/save'?>" method="post">
                <input type="hidden" name="Id_Usuario" value="<?=$data->Id?>">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="tipo">Tipo de Cliente</label>
                            <input type="text" name="tipo" id="id_tipo" class="form-control"
                                value="<?=$data->IdTipo?>">
                        </div>
                    </div>
                    <div class="col-sm-8">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="nombres">Nombres</label>
                            <input type="text" name="nombres" id="id_nombre" class="form-control"
                                value="<?=$data->Nombres?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="apellidos">apellidos</label>
                            <input type="text" name="apellidos" id="id_descripcion" class="form-control"
                                value="<?=$data->Apellidos?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="direccion">direccion</label>
                            <input type="text" name="direccion" id="id_descripcion" class="form-control"
                                value="<?=$data->Direccion?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="telf">Telefono</label>
                            <input type="text" name="telf" id="id_nombre" class="form-control"
                                value="<?=$data->Telf?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="usuario">Usuario</label>
                            <input type="text" name="usuario" id="id_usuario" class="form-control"
                                value="<?=$data->Usuario?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="clave">Clave</label>
                            <input type="text" name="clave" id="id_descripcion" class="form-control"
                                value="<?=$data->Clave?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="correo">Correo</label>
                            <input type="text" name="correo" id="id_nombre" class="form-control"
                                value="<?=$data->Correo?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="fechacreacion">FechaCreacion</label>
                            <input type="text" name="fechacreacion" id="id_usuario" class="form-control"
                                value="<?=$data->FCreacion?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="FEliminacion">FEliminacion</label>
                            <input type="text" name="FEliminacion" id="id_descripcion" class="form-control"
                                value="<?=$data->FEliminacion?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group form-check">
                            <input type="checkbox" name="estado" id="id_estado" class="form-check-input"
                            <?= ($data->Estado == 1) ? 'checked' : '' ?>>
                            <label class="form-check-label" for="exampleCheck1">Estado</label>
                        </div>
                    </div>
                    <div class="form-group ">
                    <div class="col-sm-8">
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Guardar </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>