<?php
$this->layout('../layouts/layout',
[
    'titles'=> 'FBMinimarket | Usuarios'
]);
?>
<?php $this->push('styles');?>
<!-- //link de css  -->
<?php $this->end(); ?>

<?php $this->start('contents');?>

<div class="container">
    <h1>Usuario</h1>
    <div class="row">
        <div class="col-sm-4 form-group">
            <a is-modal="true" href=" <?=URL . 'usuario/detail'?>" class="btn btn-primary btn-block">Nuevo</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width:5%;">ID</th>
                        <th style="width:5%;">IdTipo</th>
                        <th style="width:15%;">Nombre</th>
                        <th style="width:20%;">Apellidos</th>
                        <th style="width:15%;">Direccion</th>
                        <th style="width:15%;">Telf</th>
                        <th style="width:15%;">Correo</th>
                        <th style="width:10%;"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php  foreach($data as $row):  ?>
                    <tr>
                        <td> <?=$row->Id ?></td>
                        <td> <?=$row->IdTipo ?></td>
                        <td> <?=$row->Nombres ?></td>
                        <td> <?=$row->Apellidos ?></td>
                        <td> <?=$row->Direccion ?></td>
                        <td> <?=$row->Telf ?></td>
                        <td> <?=$row->Correo ?></td>
                        <td>
                        <a is-modal="true" href="<?=URL. "usuario/detail/{$row->Id}" ?>" class="btntb btn-success btn-sm"> <i class="fa fa-pencil"></i></a>
                        <a href="<?=URL. "usuario/delete/{$row->Id}" ?>" class="btntb btn-danger btn-sm"> <i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <?php  endforeach;  ?>
                </tbody>
            </table>
        </div>
        <br>
    </div>
</div>
<?php $this->end(); ?>


<?php $this->start('myModal') ?>
<?php
$title = 'Usuario Detalle - Insertar';
$size = MUYGRANDE;
include MAINPATH . 'app/views/layouts/partials/_areaModalCrud.phtml';
?>
<?php $this->stop() ?>


<?php $this->push('scripts');?>
  <script src="<?=URL.'js/scripts/modal_crud.js'?>"></script>
<?php $this->end(); ?>