<!DOCTYPE html>
<html>

<!-- molla/index-22.html  22 Nov 2019 10:01:54 GMT -->
<head>
	<title><?=$this->e($titles)?> </title>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="Molla - Bootstrap eCommerce Template">
    <meta name="author" content="p-themes">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="<?=URL.'images/icons/apple-touch-icon.png' ?>">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=URL.'images/icons/favicon-32x32.png' ?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=URL.'images/icons/favicon-16x16.png' ?>">
    <link rel="manifest" href="<?=URL.'images/icons/site.html' ?>">
    <link rel="mask-icon" href="<?=URL.'images/icons/safari-pinned-tab.svg' ?>" color="#666666">
    <link rel="shortcut icon" href="<?=URL.'images/icons/favicon.ico' ?>">
    <meta name="apple-mobile-web-app-title" content="Molla">
    <meta name="application-name" content="Molla">
    <meta name="msapplication-TileColor" content="#cc9966">
    <meta name="msapplication-config" content="<?=URL.'images/icons/browserconfig.xml' ?>">
    <meta name="theme-color" content="#ffffff">
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="<?=URL.'css/bootstrap.min.css' ?>">
    <link rel="stylesheet" href="<?=URL.'css/plugins/owl-carousel/owl.carousel.css' ?>">
    <link rel="stylesheet" href="<?=URL.'css/plugins/magnific-popup/magnific-popup.css' ?>">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="<?=URL.'css/style.css' ?>">
    <link rel="stylesheet" href="<?=URL.'css/skins/skin-demo-22.css' ?>">
    <link rel="stylesheet" href="<?=URL.'css/demos/demo-22.css' ?>">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <?= $this->section('styles') ?>
</head>
<body>
    <div class="page-wrapper">
        <?php require_once MAINPATH.'app/views/layouts/partials/_header.phtml' ?>
        <?=$this->section('contents')?>
        <?php require_once MAINPATH.'app/views/layouts/partials/_footer.phtml' ?>
    </div>
    <?=$this->section('myModal')?>
 	<!-- Plugins JS File -->
    <script src="<?=URL.'js/jquery.min.js' ?>"></script>
    <script src="<?=URL.'js/bootstrap.bundle.min.js' ?>"></script>
    <script src="<?=URL.'js/jquery.hoverIntent.min.js' ?>"></script>
    <script src="<?=URL.'js/jquery.waypoints.min.js' ?>"></script>
    <script src="<?=URL.'js/superfish.min.js' ?>"></script>
    <script src="<?=URL.'js/owl.carousel.min.js' ?>"></script>
    <script src="<?=URL.'js/bootstrap-input-spinner.js' ?>"></script>
    <script src="<?=URL.'js/jquery.magnific-popup.min.js' ?>"></script>
    <!-- Main JS File -->
    <script src="<?=URL.'js/main.js' ?>"></script>
    <?= $this->section('scripts') ?>
</body>

<!-- molla/index-22.html  22 Nov 2019 10:02:10 GMT -->
</html>